### ISSUE TITLE
pak does not find linux binaries

### ISSUE THREAD

**Issue by jeroen** [r-universe-org/help#568]
See: https://fosstodon.org/@sckottie/114044114419064713

We should figure out how pak finds Linux binary packages, so we can serve them if available.

Currently the user would manually have to `options(repos="https://jeroen.r-universe.dev/bin/linux/noble/4.5")` but it would be nice if it would work out of the box for:

```yaml
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          extra-repositories: https://paws-r.r-universe.dev
```
